version: "3"

services:
    ricette-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
    ricette-seguite-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
    connessioni-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
    api-gateway:
        build:
            context: ./
            dockerfile: Dockerfile_api-gateway
        ports:
            - "8080:8080"
        networks:
            - asw-net
        depends_on:
            - consul
    ricette:
        build:
            context: ./
            dockerfile: Dockerfile_ricette
        networks:
            - asw-net
        depends_on:
            - ricette-mysql
            - consul
    ricette-seguite:
        build:
            context: ./
            dockerfile: Dockerfile_ricette-seguite
        networks:
            - asw-net
        depends_on:
            - ricette-seguite-mysql
            - consul
    connessioni:
        build:
            context: ./
            dockerfile: Dockerfile_connessioni
        networks:
            - asw-net
        depends_on:
            - connessioni-mysql
            - consul
    consul:
        image: consul:latest
        networks:
            - asw-net
    zookeeper:
    	image: wurstmeister/zookeeper
    	ports:
    	    - "2181:2181"
    kafka:
    	image: wurstmeister/kafka:latest
    	depends_on:
    	    - "zookeeper"
    	ports:
    	    - "9092:9092"   
    	environment:
    	    KAFKA_ADVERTISED_HOST_NAME: 10.11.1.121
    	    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    	    KAFKA_CREATE_TOPICS: "ricette:4:1,connessioni:4:1"
    	volumes:
    	    - /var/run/docker.sock:/var/run/docker.sock
    	networks:
    	    - asw-net
    	    

networks:
    asw-net:
        driver: bridge
