version: "3"

services:
    ricette-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
    ricette-seguite-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
    connessioni-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
            
            
    api-gateway:
        build:
            context: ./api-gateway
        ports:
            - "8080:8080"
        networks:
            - asw-net
        depends_on:
            - consul
    ricette:
        build:
            context: ./ricette
        networks:
            - asw-net
        depends_on:
            - ricette-mysql
            - consul
            - kafka
    ricette-seguite:
        build:
            context: ./ricette-seguite
        networks:
            - asw-net
        depends_on:
            - ricette-seguite-mysql
            - consul
            - kafka
    connessioni:
        build:
            context: ./connessioni
        networks:
            - asw-net
        depends_on:
            - connessioni-mysql
            - consul
            - kafka
            
            
    consul:
        image: consul:latest
        networks:
            - asw-net
    zookeeper:
        image: wurstmeister/zookeeper
        networks:
            - asw-net
    kafka:
        image: wurstmeister/kafka
        networks:
            - asw-net
        depends_on:
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "ricette:4:1,connessioni:4:1"
            
networks:
    asw-net:
        driver: bridge
