version: "3"

services:
    ricette-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
    ricette-seguite-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
    connessioni-mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - asw-net
    api-gateway:
        build:
            context: ./
            dockerfile: Dockerfile_api-gateway
        ports:
            - "8080:8080"
        networks:
            - asw-netw
        depends_on:
            - consul
    ricette:
        build:
            context: ./
            dockerfile: Dockerfile_ricette
        networks:
            - asw-net
        depends_on:
            - ricette-mysql
            - consul
    ricette-seguite:
        build:
            context: ./
            dockerfile: Dockerfile_ricette-seguite
        networks:
            - asw-net
        depends_on:
            - ricette-seguite-mysql
            - consul
    connessioni:
        build:
            context: ./
            dockerfile: Dockerfile_connessioni
        networks:
            - asw-net
        depends_on:
            - connessioni-mysql
            - consul
    consul:
        image: consul:latest
        networks:
            - asw-net

networks:
    asw-net:
        driver: bridge
